/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VetsIndexRouteImport } from './routes/vets.index'
import { Route as VetsIdRouteImport } from './routes/vets.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsIndexRoute = VetsIndexRouteImport.update({
  id: '/vets/',
  path: '/vets/',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsIdRoute = VetsIdRouteImport.update({
  id: '/vets/$id',
  path: '/vets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/clinic': typeof ClinicRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verification': typeof VerificationRoute
  '/book/$id': typeof BookIdRoute
  '/vets/$id': typeof VetsIdRoute
  '/vets/': typeof VetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/clinic': typeof ClinicRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verification': typeof VerificationRoute
  '/book/$id': typeof BookIdRoute
  '/vets/$id': typeof VetsIdRoute
  '/vets': typeof VetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/clinic': typeof ClinicRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/pets': typeof PetsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/verification': typeof VerificationRoute
  '/book/$id': typeof BookIdRoute
  '/vets/$id': typeof VetsIdRoute
  '/vets/': typeof VetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/clinic'
    | '/home'
    | '/landing'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/role'
    | '/settings'
    | '/staff'
    | '/verification'
    | '/book/$id'
    | '/vets/$id'
    | '/vets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/clinic'
    | '/home'
    | '/landing'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/role'
    | '/settings'
    | '/staff'
    | '/verification'
    | '/book/$id'
    | '/vets/$id'
    | '/vets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/clinic'
    | '/home'
    | '/landing'
    | '/notifications'
    | '/pets'
    | '/profile'
    | '/role'
    | '/settings'
    | '/staff'
    | '/verification'
    | '/book/$id'
    | '/vets/$id'
    | '/vets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  ClinicRoute: typeof ClinicRoute
  HomeRoute: typeof HomeRoute
  LandingRoute: typeof LandingRoute
  NotificationsRoute: typeof NotificationsRoute
  PetsRoute: typeof PetsRoute
  ProfileRoute: typeof ProfileRoute
  RoleRoute: typeof RoleRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  VerificationRoute: typeof VerificationRoute
  BookIdRoute: typeof BookIdRoute
  VetsIdRoute: typeof VetsIdRoute
  VetsIndexRoute: typeof VetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/': {
      id: '/vets/'
      path: '/vets'
      fullPath: '/vets/'
      preLoaderRoute: typeof VetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/$id': {
      id: '/vets/$id'
      path: '/vets/$id'
      fullPath: '/vets/$id'
      preLoaderRoute: typeof VetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  ClinicRoute: ClinicRoute,
  HomeRoute: HomeRoute,
  LandingRoute: LandingRoute,
  NotificationsRoute: NotificationsRoute,
  PetsRoute: PetsRoute,
  ProfileRoute: ProfileRoute,
  RoleRoute: RoleRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  VerificationRoute: VerificationRoute,
  BookIdRoute: BookIdRoute,
  VetsIdRoute: VetsIdRoute,
  VetsIndexRoute: VetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
